name: Unit Tests
"on": 
  - push
  - workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wntrblm/nox@2023.04.22
      - uses: Gr1N/setup-poetry@v8
      - run: nox -s lint
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wntrblm/nox@2023.04.22
      - uses: Gr1N/setup-poetry@v8
      - run: nox -s unit
