name: build
"on": 
  - push
jobs:
  test:
    uses: ./.github/workflows/unit-test.yml
  build:
    name: Build distributables
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - uses: Gr1N/setup-poetry@v8
    - name: Build the distribution
      run: poetry build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
  
    environment:
      name: testpypi
      url: https://test.pypi.org/p/sqlalchemy-pglogical
  
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
  
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sqlalchemy_pglogical  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1