name: Unit Tests
run-name: asdf
"on": 
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: excitedleigh/setup-nox@v2.0.0
      - run: nox -s lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: excitedleigh/setup-nox@v2.0.0
      - run: nox -s unit
